export const MOVE_CARD: 'MOVE_CARD' = 'MOVE_CARD';
export const ADD_ITEMS_TO_CONSTRUCTOR: 'ADD_ITEMS_TO_CONSTRUCTOR' = 'ADD_ITEMS_TO_CONSTRUCTOR'
export const DELTE_ITEM_FROM_CONSTRUCTOR: 'DELTE_ITEM_FROM_CONSTRUCTOR' = 'DELTE_ITEM_FROM_CONSTRUCTOR'
export const CLEAR_CONSTRUCTOR: 'CLEAR_CONSTRUCTOR' = 'CLEAR_CONSTRUCTOR'

export const GET_ITEMS_REQUEST: 'GET_ITEMS_REQUEST' = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS' = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED: 'GET_ITEMS_FAILED' = 'GET_ITEMS_FAILED';
export const GET_CURRENT_ITEM: 'GET_CURRENT_ITEM' = 'GET_CURRENT_ITEM';
export const CLOSE_CURRENT_ITEM: 'CLOSE_CURRENT_ITEM' = 'CLOSE_CURRENT_ITEM'

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';
export const CLOSE_ORDER_MODAL: 'CLOSE_ORDER_MODAL' = 'CLOSE_ORDER_MODAL'

export const GET_USER_REQUEST_START: 'GET_USER_REQUEST_START' = 'GET_USER_REQUEST_START';
export const GET_USER_REQUEST_END: 'GET_USER_REQUEST_END' = 'GET_USER_REQUEST_END';
export const GET_USER_LOGIN_REQUEST: 'GET_USER_LOGIN_REQUEST' = 'GET_USER_LOGIN_REQUEST';
export const GET_USER_LOGIN_SUCCESS: 'GET_USER_LOGIN_SUCCESS' = 'GET_USER_LOGIN_SUCCESS';
export const GET_USER_LOGIN_FAILED: 'GET_USER_LOGIN_FAILED' = 'GET_USER_LOGIN_FAILED';
export const GET_USER_AUTH_SUCCESS: 'GET_USER_AUTH_SUCCESS' = 'GET_USER_AUTH_SUCCESS';
export const GET_LOGOUT: 'GET_LOGOUT' = 'GET_LOGOUT';
export const GET_LOGOUT_FAILED: 'GET_LOGOUT_FAILED' = 'GET_LOGOUT_FAILED';
export const GET_USER_REFRESH_DATA_SUCCESS: 'GET_USER_REFRESH_DATA_SUCCESS' = 'GET_USER_REFRESH_DATA_SUCCESS';
export const GET_USER_REFRESH_DATA_FAILED: 'GET_USER_REFRESH_DATA_FAILED' = 'GET_USER_REFRESH_DATA_FAILED';
export const SEND_FORGOT_PASS_MESS_SUCCES: 'SEND_FORGOT_PASS_MESS_SUCCES' = 'SEND_FORGOT_PASS_MESS_SUCCES';
export const SEND_FORGOT_PASS_MESS_FAILED: 'SEND_FORGOT_PASS_MESS_FAILED' = 'SEND_FORGOT_PASS_MESS_FAILED';
export const SEND_RESET_PASS_MESS_SUCCES: 'SEND_RESET_PASS_MESS_SUCCES' = 'SEND_RESET_PASS_MESS_SUCCES';
export const SEND_RESET_PASS_MESS_FAILED: 'SEND_RESET_PASS_MESS_FAILED' = 'SEND_RESET_PASS_MESS_FAILED';

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';

export const WS_AUTH_CONNECTION_START: 'WS_AUTH_CONNECTION_START' = 'WS_AUTH_CONNECTION_START';
export const WS_AUTH_CONNECTION_SUCCESS: 'WS_AUTH_CONNECTION_SUCCESS' = 'WS_AUTH_CONNECTION_SUCCESS';
export const WS_AUTH_CONNECTION_ERROR: 'WS_AUTH_CONNECTION_ERROR' = 'WS_AUTH_CONNECTION_ERROR';
export const WS_AUTH_CONNECTION_CLOSED: 'WS_AUTH_CONNECTION_CLOSED' = 'WS_AUTH_CONNECTION_CLOSED';
export const WS_AUTH_GET_MESSAGE: 'WS_AUTH_GET_MESSAGE' = 'WS_AUTH_GET_MESSAGE';
export const WS_AUTH_SEND_MESSAGE: 'WS_AUTH_SEND_MESSAGE' = 'WS_AUTH_SEND_MESSAGE';